export const restaurantDetails = [
  {
    id: 1,
    name: "Chinese Wok",
    rating: "3.4",
    deliveryTime: "35-40mins",
    cuisines: "Chinese , Arabian",
    imageId: "e0839ff574213e6f35b3899ebf1fc597",
  },
  {
    id: 2,
    name: "Mithaas",
    rating: "4.3",
    deliveryTime: "35-40mins",
    cuisines: "Sweets , Snacks, Bakery",
    imageId: "tffkatewxt8zcieztpzx",
  },
  {
    id: 3,
    name: "Mr Brown",
    rating: "4.5",
    deliveryTime: "25-30mins",
    cuisines: "FastFood , Snacks, Bakery",
    imageId: "vlbu10drqjjvjsd043zc",
  },
  {
    id: 4,
    name: "Hira Sweets",
    rating: "4.4",
    deliveryTime: "35-40mins",
    cuisines: "SouthIndian Chinese",
    imageId: "eofyjfawwx8dt7qvsrr2",
  },
  {
    id: 5,
    name: "Chinese Wok",
    rating: "3.4",
    deliveryTime: "35-40mins",
    cuisines: "Chinese , Arabian",
    imageId: "e0839ff574213e6f35b3899ebf1fc597",
  },
  {
    id: 6,
    name: "Mithaas",
    rating: "4.3",
    deliveryTime: "35-40mins",
    cuisines: "Sweets , Snacks, Bakery",
    imageId: "tffkatewxt8zcieztpzx",
  },
  {
    id: 7,
    name: "Mr Brown",
    rating: "4.5",
    deliveryTime: "25-30mins",
    cuisines: "FastFood , Snacks, Bakery",
    imageId: "vlbu10drqjjvjsd043zc",
  },
  {
    id: 8,
    name: "Hira Sweets",
    rating: "4.4",
    deliveryTime: "35-40mins",
    cuisines: "SouthIndian Chinese",
    imageId: "eofyjfawwx8dt7qvsrr2",
  },
  {
    id: 9,
    name: "Chinese Wok",
    rating: "3.4",
    deliveryTime: "35-40mins",
    cuisines: "Chinese , Arabian",
    imageId: "e0839ff574213e6f35b3899ebf1fc597",
  },
  {
    id: 10,
    name: "Mithaas",
    rating: "4.3",
    deliveryTime: "35-40mins",
    cuisines: "Sweets , Snacks, Bakery",
    imageId: "tffkatewxt8zcieztpzx",
  },
  {
    id: 11,
    name: "Mr Brown",
    rating: "4.5",
    deliveryTime: "25-30mins",
    cuisines: "FastFood , Snacks, Bakery",
    imageId: "vlbu10drqjjvjsd043zc",
  },
  {
    id: 12,
    name: "Hira Sweets",
    rating: "4.4",
    deliveryTime: "35-40mins",
    cuisines: "SouthIndian Chinese",
    imageId: "eofyjfawwx8dt7qvsrr2",
  },
];
